# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('result', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ChZapping',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report.BaseReport')),
                ('remote_time', models.DateTimeField()),
                ('first_stop_time', models.DateTimeField()),
                ('second_stop_time', models.DateTimeField()),
                ('edge_time', models.DateTimeField()),
            ],
            bases=('report.basereport',),
        ),
        migrations.CreateModel(
            name='ImageMatch',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report.BaseReport')),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=('report.basereport',),
        ),
        migrations.CreateModel(
            name='UIReaction',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report.BaseReport')),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remote_time', models.DateTimeField()),
                ('match_time', models.DateTimeField()),
            ],
            bases=('report.basereport',),
        ),
        migrations.AddField(
            model_name='basereport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
