# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaselist',
            name='case',
            field=models.CharField(max_length=50, verbose_name='중분류'),
        ),
        migrations.AlterField(
            model_name='testcaselist',
            name='context',
            field=models.CharField(max_length=200, verbose_name='상세화면'),
        ),
        migrations.AlterField(
            model_name='testcaselist',
            name='priority',
            field=models.CharField(max_length=50, verbose_name='중요도'),
        ),
        migrations.AlterField(
            model_name='testcaselist',
            name='result',
            field=models.CharField(max_length=50, verbose_name='측정결과'),
        ),
        migrations.AlterField(
            model_name='testcaselist',
            name='suite',
            field=models.CharField(max_length=50, verbose_name='대분류'),
        ),
        migrations.AlterField(
            model_name='testcaselist',
            name='task',
            field=models.CharField(max_length=100, verbose_name='소분류'),
        ),
    ]
