# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0002_auto_20171030_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaselist',
            name='context',
            field=models.TextField(verbose_name='상세화면'),
        ),
    ]
