# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0004_auto_20171030_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaselist',
            name='result',
            field=models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL'), ('NONE', 'NONE')], default='NONE', max_length=10, verbose_name='측정결과'),
        ),
    ]
