# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=10)),
                ('firmware', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('basedevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.BaseDevice')),
                ('mac_address', models.CharField(max_length=50, unique=True)),
            ],
            bases=('device.basedevice',),
        ),
        migrations.CreateModel(
            name='RemoteController',
            fields=[
                ('basedevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.BaseDevice')),
            ],
            bases=('device.basedevice',),
        ),
        migrations.CreateModel(
            name='Settopbox',
            fields=[
                ('basedevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.BaseDevice')),
                ('mac_address', models.CharField(max_length=50, unique=True)),
            ],
            bases=('device.basedevice',),
        ),
    ]
