# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_basedevice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedevice',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='basedevice',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
