# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.CharField(max_length=200),
        ),
    ]
