# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('device', '0003_auto_20171023_1714'),
        ('project', '0002_auto_20171024_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdevice',
            name='device',
        ),
        migrations.RemoveField(
            model_name='projectdevice',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='project_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.BaseDevice'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
        migrations.DeleteModel(
            name='ProjectDevice',
        ),
        migrations.DeleteModel(
            name='ProjectMember',
        ),
    ]
